services:
    matrix_service:
        build:
          context: .
          dockerfile: Dockerfile
        platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/matrix_service/.ccache
          - CORES_DIR=/cores
          - USERVER_DISABLE_STACK_USAGE_MONITOR=1
          - USERVER_DISABLE_USERFAULTFD=1
        volumes:
          - .:/matrix_service:rw
        ports:
          - 8080:8080
        working_dir: /matrix_service
        command: ["make", "cmake-debug", "build-debug", "${MAKE_TARGET:-start-debug}"]
    swagger-ui:
      image: swaggerapi/swagger-ui:v5.17.14
      container_name: swagger-ui
      depends_on:
        matrix_service:
          condition: service_started
      ports:
        - "8081:8080"
      environment:
        SWAGGER_JSON: /spec/openapi.yaml
      volumes:
        - ./openapi.yaml:/spec/openapi.yaml:ro
