services:
    matrix_service:
        build:
          context: .
        platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/matrix_service/.ccache
          - CORES_DIR=/cores
          - USERVER_DISABLE_STACK_USAGE_MONITOR=1
          - USERVER_DISABLE_USERFAULTFD=1
        volumes:
          - .:/matrix_service:rw
        ports:
          - 8080:8080
        working_dir: /matrix_service
        command: ["make", "cmake-debug", "build-debug", "${MAKE_TARGET:-start-debug}"]
